# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorcb < Formula
  desc "CLI tool for reinforced concrete beam design based on NSCP"
  homepage "https://github.com/alexiusacademia/gorcb"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexiusacademia/gorcb/releases/download/v1.1.0/gorcb_1.1.0_darwin_amd64.tar.gz"
      sha256 "9524acd152f799dc629062c0ab2dc7946ffb1ef513577ae269f2cfbb0ed59d01"

      def install
        bin.install "gorcb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexiusacademia/gorcb/releases/download/v1.1.0/gorcb_1.1.0_darwin_arm64.tar.gz"
      sha256 "25c1c28d0420f70759e3c331f79469f6ca8ef592aa65c4851c4e7afc927aa576"

      def install
        bin.install "gorcb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexiusacademia/gorcb/releases/download/v1.1.0/gorcb_1.1.0_linux_amd64.tar.gz"
      sha256 "3e0a151adac62c41cf1b76ddb28d96fc5b5eb4b0f8ee28bdc5313ab1cffef598"
      def install
        bin.install "gorcb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexiusacademia/gorcb/releases/download/v1.1.0/gorcb_1.1.0_linux_arm64.tar.gz"
      sha256 "298b71346f438997ed02b1ac2505900ec4f7f22cbc2a932b39d99f96638d27b7"
      def install
        bin.install "gorcb"
      end
    end
  end

  test do
    system "#{bin}/gorcb", "version"
  end
end
