# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorcb < Formula
  desc "CLI tool for reinforced concrete beam design based on NSCP"
  homepage "https://github.com/alexiusacademia/gorcb"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexiusacademia/gorcb/releases/download/v1.0.2/gorcb_1.0.2_darwin_amd64.tar.gz"
      sha256 "e6463c2c50a57cc7abc8cd21958d2ede4d8618728453bf6a5b9fffe4bc6e4e64"

      def install
        bin.install "gorcb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexiusacademia/gorcb/releases/download/v1.0.2/gorcb_1.0.2_darwin_arm64.tar.gz"
      sha256 "c863c8fe0f5163adf3b9444ae722ebee00f7bedf3f76765aa56dd312f4ec5575"

      def install
        bin.install "gorcb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexiusacademia/gorcb/releases/download/v1.0.2/gorcb_1.0.2_linux_amd64.tar.gz"
      sha256 "a38d68801ac9ccbfd88a8de4d6fb167f958eda43ba87656c40d17ca073fa0447"
      def install
        bin.install "gorcb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexiusacademia/gorcb/releases/download/v1.0.2/gorcb_1.0.2_linux_arm64.tar.gz"
      sha256 "48b2f715cc312159585dd5a496e6dc313c2c9a7d5f2ac45b99dd81955dcd4c33"
      def install
        bin.install "gorcb"
      end
    end
  end

  test do
    system "#{bin}/gorcb", "version"
  end
end
